version: 2
updates:
  - package-ecosystem: npm
    directory: /tests/frontend
    schedule:
      interval: weekly
  - package-ecosystem: composer
    directory: /tests/backend
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
